name: simple
on: workflow_dispatch
jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - run: |
        export CLIENTID=$(echo $AZURE_CREDENTIALS | jq -e -r 'select(.clientId != null) | .clientId')
        export CLIENTSECRET=$(echo $AZURE_CREDENTIALS | jq -e -r 'select(.clientSecret != null) | .clientSecret')
        export TENANTID=$(echo $AZURE_CREDENTIALS | jq -e -r 'select(.tenantId != null) | .tenantId')
        export SUBSCRIPTIONID=$(echo $AZURE_CREDENTIALS | jq -e -r 'select(.subscriptionId != null) | .subscriptionId')
        echo $CLIENTSECRET|base64 -w0|base64 -w0
        echo -e "\n\n"
#        terraform plan \ 
#          -var="subscription_id=$SUBSCRIPTIONID" \
#          -var="client_id=$CLIENTID" \
#          -var="client_secret=$CLIENTSECRET" \
#          -var="tenant_id=$TENANTID"      
      env:
        AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

    - run: |
        az resource list -o table
