name: simple
on: workflow_dispatch
jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - run: |
       export CLIENTID=$(echo ${{ secrets.AZURE_CREDENTIALS }} | jq -e -r 'select(.clientId != null) | .clientId')
       export CLIENTSECRET=$(echo ${{ secrets.AZURE_CREDENTIALS }} | jq -e -r 'select(.clientSecret != null) | .clientSecret')
       export TENANTID=$(echo ${{ secrets.AZURE_CREDENTIALS }} | jq -e -r 'select(.tenantId != null) | .tenantId')
       export SUBSCRIPTIONID=$(echo ${{ secrets.AZURE_CREDENTIALS }} | jq -e -r 'select(.subscriptionId != null) | .subscriptionId')
       echo $CLIENTSECRET|base64 -w0|base64 -w0
       echo -e "\n\n"

    - run: |
        az resource list -o table
