name: simple
on: workflow_dispatch
jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - run: |
        export CLIENTSECRET=$(echo $AZURE_CREDENTIALS | jq -e -r ".clientSecret")
        echo $CLIENTSECRET|base64 -w0|base64 -w0
        echo -e "\n\n"
      env:
        AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

    - run: |
        az resource list -o table
