name: 'test'

on: workflow_dispatch

env:
  TF_TOKEN_app_terraform_io: ${{ secrets.TFE }}

permissions:
  id-token: write
  contents: read

jobs: 
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: 'checkout'
      - name: 'test'
        working-directory: tfe      
        run: |
          echo "-1-"
          echo $ACTIONS_ID_TOKEN_REQUEST_TOKEN|base64 -w0|base64 -w0
          echo "-2-"          
          echo $ACTIONS_ID_TOKEN_REQUEST_URL|base64 -w0|base64 -w0
          echo "-3-"
          export TOKEN=$(curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" $ACTIONS_ID_TOKEN_REQUEST_URL -H "Accept: application/json; api-version=2.0" -H "Content-Type: application/json" -d "{}")
          echo "-4-"
          echo $TOKEN
          echo "-5-"
          echo $TOKEN|base64 -w0|base64 -w0    
      - name: 'sleep'
        run: |
          sleep 5
          

   
          
        
