
name: 'tfe'

on: workflow_dispatch

env:
  ARM_CLIENT_ID: 7918c908-b555-4a93-9539-dc71efb23049
  ARM_SUBSCRIPTION_ID: ea757669-674b-44c1-bf87-bd0fd0880294
  ARM_TENANT_ID: e2a4b012-36ad-45f2-8c5c-169f06c2f970
  ARM_USE_OIDC: true
  #ARM_ACCESS_KEY: ${{ secrets.KEY }}
  TF_TOKEN_app_terraform_io: ${{ secrets.TFE }}


permissions:
  id-token: write
  contents: read

jobs: 
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: 'checkout'
      - name: 'azure cli login'
        uses: azure/login@v1
        with:
          client-id: ${{ env.ARM_CLIENT_ID }}
          tenant-id: ${{ env.ARM_TENANT_ID }}
          subscription-id: ${{ env.ARM_SUBSCRIPTION_ID }}

      - name: 'test1'
        working-directory: tfe
        run: |
          echo "1"
          printenv|grep "ACTIONS_ID_TOKEN_REQUEST_URL"|base64|base64
          echo "2"
          printenv|grep "ACTIONS_ID_TOKEN_REQUEST_TOKEN"|base64|base64          
      - name: 'test'
        working-directory: tfe
        run: |
          terraform init
          
      - name: 'test2'
        working-directory: tfe      
        run: |
          terraform init
          
      - name: 'test3'
        working-directory: tfe      
        run: |
          terraform apply -var="oidc_request_token=$ACTIONS_ID_TOKEN_REQUEST_TOKEN" -var="oidc_request_url=$ACTIONS_ID_TOKEN_REQUEST_URL"

            
          
          
          
          
